version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: ./packages/api
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKERS: kafka:9092
      PORT: 5000
      NODE_ENV: development
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRES_IN: 24h
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: your-aws-access-key
      AWS_SECRET_ACCESS_KEY: your-aws-secret-key
      S3_BUCKET_NAME: jobquest-cv-uploads
      JOBS_TABLE: Jobs
      SARKARI_JOBS_TABLE: SarkariJobs
      ADMINS_TABLE: Admins
      SUBSCRIPTIONS_TABLE: Subscriptions
      REDIS_URL: redis://redis:6379
      ADMIN_EMAIL: admin@jobquest.com
      ADMIN_PASSWORD: admin123
    depends_on:
      - kafka
      - redis